import { isAdminMutationRequest } from '../../../lib/no11-admin-auth.js';

const DEFAULT_TEAM=[
  {id:'eda-dincer',name:'Eda Dinçer',role:'Kurucu · Eğitmen',bio:'13 yıldır Pilates eğitmenliği yapıyorum. Classical Pilates metoduyla, kişiye özel ve bilinçli hareket yaklaşımıyla çalışıyorum.',image:'https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/eda.webp',active:true,featured:true},
  {id:'burcu-kenar',name:'Burcu Kenar',role:'Eğitmen',bio:'Dört yıldır Pilates eğitmenliği yapıyorum. Balanced Body, hamilelik, bel-boyun problemleri, yoga ve fitness alanlarında eğitimlerim bulunuyor.',image:'https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/burcu.webp',active:true,featured:false},
  {id:'irem-bozkaya',name:'İrem Bozkaya',role:'Fizyoterapist · Eğitmen',bio:'İstanbul Üniversitesi-Cerrahpaşa Fizyoterapi ve Rehabilitasyon mezunuyum. Kişiye özel egzersiz planlamasıyla daha güçlü ve sağlıklı bir yaşama eşlik ediyorum.',image:'https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/irem.webp',active:true,featured:false}
];
const KEY='no11:team';
function env(){return {url:process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL,token:process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN}}
async function command(args){var e=env();if(!e.url||!e.token)throw new Error('storage');var response=await fetch(e.url,{method:'POST',headers:{authorization:'Bearer '+e.token,'content-type':'application/json'},body:JSON.stringify(args),cache:'no-store'});if(!response.ok)throw new Error('storage');return (await response.json()).result}
const MAX_BODY_BYTES=4*1024*1024;
function cleanText(value,max){const text=String(value||'').trim();if(text.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(text))throw new Error('invalid');return text}
function cleanImage(value){const image=String(value||'').trim();if(!image)return '';if(image.length>3*1024*1024)throw new Error('invalid');if(/^https:\/\/[^\s]+$/i.test(image))return image;if(/^data:image\/(?:jpeg|png|webp);base64,[A-Za-z0-9+/=\r\n]+$/i.test(image))return image;throw new Error('invalid')}
function cleanTeam(team){if(!Array.isArray(team)||team.length>12)throw new Error('invalid');return team.map((member,index)=>{if(!member||typeof member!=='object'||Array.isArray(member))throw new Error('invalid');const allowed=new Set(['id','name','role','bio','image','active','featured']);if(Object.keys(member).some((key)=>!allowed.has(key)))throw new Error('invalid');const clean={id:cleanText(member.id||`team-${index}`,80),name:cleanText(member.name,100),role:cleanText(member.role,120),bio:cleanText(member.bio,2000),image:cleanImage(member.image),active:member.active!==false,featured:member.featured===true};if(!clean.id||!clean.name||!clean.role)throw new Error('invalid');return clean})}
async function readBody(request){const declared=Number(request.headers.get('content-length')||0);if(declared>MAX_BODY_BYTES)throw new Error('too_large');const raw=await request.text();if(Buffer.byteLength(raw,'utf8')>MAX_BODY_BYTES)throw new Error('too_large');return JSON.parse(raw||'{}')}
export async function GET(){try{var raw=await command(['GET',KEY]);return Response.json({team:raw?JSON.parse(raw):DEFAULT_TEAM,persistent:true},{headers:{'cache-control':'no-store'}})}catch(error){return Response.json({team:DEFAULT_TEAM,persistent:false},{headers:{'cache-control':'no-store'}})}}
export async function PUT(request){if(!isAdminMutationRequest(request))return Response.json({error:'unauthorized'},{status:401,headers:{'cache-control':'no-store'}});try{const body=await readBody(request);const team=cleanTeam(body.team);await command(['SET',KEY,JSON.stringify(team)]);return Response.json({ok:true,team,persistent:true},{headers:{'cache-control':'no-store'}})}catch(error){return Response.json({error:error?.message==='too_large'?'payload_too_large':'invalid_team'},{status:error?.message==='too_large'?413:400,headers:{'cache-control':'no-store'}})}}
