const DEFAULT_TEAM=[
  {id:'eda-dincer',name:'Eda Dinçer',role:'Kurucu · Eğitmen',bio:'13 yıldır Pilates eğitmenliği yapıyorum. Classical Pilates metoduyla, kişiye özel ve bilinçli hareket yaklaşımıyla çalışıyorum.',image:'https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/eda.webp',active:true,featured:true},
  {id:'burcu-kenar',name:'Burcu Kenar',role:'Eğitmen',bio:'Dört yıldır Pilates eğitmenliği yapıyorum. Balanced Body, hamilelik, bel-boyun problemleri, yoga ve fitness alanlarında eğitimlerim bulunuyor.',image:'https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/burcu.webp',active:true,featured:false},
  {id:'irem-bozkaya',name:'İrem Bozkaya',role:'Fizyoterapist · Eğitmen',bio:'İstanbul Üniversitesi-Cerrahpaşa Fizyoterapi ve Rehabilitasyon mezunuyum. Kişiye özel egzersiz planlamasıyla daha güçlü ve sağlıklı bir yaşama eşlik ediyorum.',image:'https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/irem.webp',active:true,featured:false}
];
const KEY='no11:team';
function env(){return {url:process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL,token:process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN}}
async function command(args){var e=env();if(!e.url||!e.token)throw new Error('storage');var response=await fetch(e.url,{method:'POST',headers:{authorization:'Bearer '+e.token,'content-type':'application/json'},body:JSON.stringify(args),cache:'no-store'});if(!response.ok)throw new Error('storage');return (await response.json()).result}
export async function GET(){try{var raw=await command(['GET',KEY]);return Response.json({team:raw?JSON.parse(raw):DEFAULT_TEAM,persistent:true},{headers:{'cache-control':'no-store'}})}catch(error){return Response.json({team:DEFAULT_TEAM,persistent:false},{headers:{'cache-control':'no-store'}})}}
export async function PUT(request){try{var body=await request.json();if(!Array.isArray(body.team)||body.team.length>12)return Response.json({error:'invalid team'},{status:400});await command(['SET',KEY,JSON.stringify(body.team)]);return Response.json({ok:true,team:body.team,persistent:true},{headers:{'cache-control':'no-store'}})}catch(error){return Response.json({error:'save failed'},{status:500})}}
