'use client';
import {useEffect,useState} from 'react';

const services=['Birebir Pilates','Duet / İkili Pilates','Hamile Pilatesi','Omurga Odaklı Pilates','Tanışma Dersi'];
const times=['09:00','10:30','12:00','14:00','16:30','18:00','19:30'];

export default function HomePage(){
 const [menu,setMenu]=useState(false),[sent,setSent]=useState(false);
 useEffect(()=>{ document.body.style.overflow=menu?'hidden':''; return()=>{document.body.style.overflow=''} },[menu]);
 function submit(e){
   e.preventDefault(); const f=new FormData(e.currentTarget);
   const appointment={id:'NO11-'+String(Date.now()).slice(-6),name:String(f.get('name')||''),phone:String(f.get('phone')||''),email:String(f.get('email')||''),service:String(f.get('service')||'Tanışma Dersi'),date:String(f.get('date')||''),time:String(f.get('time')||''),studentNote:String(f.get('note')||''),note:String(f.get('note')||''),managerNote:'',status:'pending',createdAt:new Date().toISOString()};
   try{const items=JSON.parse(localStorage.getItem('no11-appointments')||'[]');items.unshift(appointment);localStorage.setItem('no11-appointments',JSON.stringify(items));}catch{}
   const text=`Merhaba No.11 Pilates Studio, randevu talebi oluşturmak istiyorum.\n\nAd Soyad: ${appointment.name}\nTelefon: ${appointment.phone}\nDers: ${appointment.service}\nTarih: ${appointment.date}\nSaat: ${appointment.time}\nNot: ${appointment.studentNote}`;
   setSent(true); window.open('https://wa.me/905325159211?text='+encodeURIComponent(text),'_blank','noopener,noreferrer'); e.currentTarget.reset();
 }
 return <main>
  <header className="site-nav"><a className="logo" href="#top">No.11<small>PILATES STUDIO</small></a><nav>{['hikaye','deneyim','studyo','ekip','iletisim'].map(x=><a key={x} href={'#'+x}>{({hikaye:'Hikâyemiz',deneyim:'Deneyim',studyo:'Stüdyo',ekip:'Ekip',iletisim:'İletişim'})[x]}</a>)}</nav><a className="nav-cta" href="#randevu">Randevu Al →</a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Menüyü aç">☰</button></header>
  {menu&&<div className="mobile-menu">{['hikaye','deneyim','studyo','ekip','iletisim','randevu'].map(x=><a onClick={()=>setMenu(false)} key={x} href={'#'+x}>{x==='randevu'?'Randevu Al':x[0].toUpperCase()+x.slice(1)} <span>→</span></a>)}</div>}
  <section id="top" className="hero"><video className="hero-video desktop-video" autoPlay muted loop playsInline poster="/no11-desktop-poster.webp"><source src="https://github.com/osmancan-bulat/no11-pilates-studio/releases/download/video-v1/no11-desktop-full-quality.mp4" type="video/mp4"/></video><video className="hero-video mobile-video" autoPlay muted loop playsInline poster="https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/hero-google-first-frame-mobile.webp?v=15"><source src="https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/media/no11-hero-google-mobile.mp4?v=15" type="video/mp4"/></video><div className="hero-shade"/><div className="hero-copy"><p>BURSA · NİLÜFER · BALAT</p><h1>Bedeninizi dinleyin.<em>Dengenizi keşfedin.</em></h1><a href="#randevu">İlk adımı atın →</a></div></section>
  <section id="hikaye" className="section story"><p className="eyebrow">NO.11'İN HİKÂYESİ</p><div className="story-grid"><h2>Yalnızca<br/>bir sayı<br/><em>değil.</em></h2><div><p className="lead">No.11; anıların, yolculuğun ve hayallerin simgesi. Güçlü sezgiyi, dengeyi, ilhamı ve rehberliği temsil eden kişiye özel bir hareket alanı.</p><div className="principles">{[['01','Sezgi','Kendi bedeninizi ve ihtiyaçlarınızı dinleme sanatı.'],['02','Denge','Fiziksel ve zihinsel bütünlüğün sağlandığı nokta.'],['03','Rehberlik','Uzman ellerde, size özel tasarlanmış bir yolculuk.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></div></section>
  <section id="deneyim" className="experience"><img src="https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/guidance.webp" alt="Kişiye özel pilates çalışması"/><div><p className="eyebrow">STÜDYO DENEYİMİ</p><h2>Burada her şey<br/><em>kişiye özeldir.</em></h2><p>Her ayrıntı düşünülür, her hareketin bir amacı vardır. Bedeninize özenle yaklaşan bir sistem sizi bekler.</p><a href="#randevu">Deneyimi planlayın →</a></div></section>
  <section id="studyo" className="section studio"><p className="eyebrow">STÜDYOMUZ</p><h2>Size ayrılmış <em>bir alan.</em></h2><div className="gallery"><img src="https://no11-pilates-studio-nqiww3b8y-osmancanbulat197-7442s-projects.vercel.app/images/studio-main.webp" alt="No.11 stüdyo iç mekânı"/><img src="https://no11-pilates-studio-nqiww3b8y-osmancanbulat197-7442s-projects.vercel.app/images/studio-wide.webp" alt="Pilates ekipmanları"/><img src="https://no11-pilates-studio-nqiww3b8y-osmancanbulat197-7442s-projects.vercel.app/images/studio-vertical.webp" alt="Gün ışığı alan stüdyo"/></div></section>
  <section id="ekip" className="section team"><p className="eyebrow">UZMAN REHBERLİK</p><div className="founder"><img src="https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/eda.webp" alt="Eda Dinçer"/><div><span>KURUCU · EĞİTMEN</span><h2>Eda Dinçer</h2><p>13 yıldır Pilates eğitmenliği yapan Eda Dinçer, Türkiye Cimnastik Federasyonu 1. ve 2. Kademe Pilates Antrenörüdür. Classical Pilates metoduyla kişiye özel, güvenli ve dengeli çalışmalar yürütür.</p></div></div></section>
  <section id="randevu" className="section booking"><div><p className="eyebrow">İLK ADIM</p><h2>Size ayrılmış<br/><em>bir zaman.</em></h2><p>Formu doldurun; No.11 ekibi talebinizi değerlendirip sizinle iletişime geçsin.</p></div><form onSubmit={submit}><label>Adınız Soyadınız<input required name="name" placeholder="Ad Soyad"/></label><div className="form-row"><label>Telefon<input required name="phone" type="tel" placeholder="05xx xxx xx xx"/></label><label>E-posta <small>(isteğe bağlı)</small><input name="email" type="email" placeholder="ornek@email.com"/></label></div><label>Ders tercihiniz<select required name="service" defaultValue=""><option value="" disabled>Bir ders türü seçin</option>{services.map(x=><option key={x}>{x}</option>)}</select></label><div className="form-row"><label>Tarih<input required name="date" type="date"/></label><label>Saat<select required name="time" defaultValue=""><option value="" disabled>Saat seçin</option>{times.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Notunuz <small>(isteğe bağlı)</small><textarea name="note" placeholder="Varsa hedefiniz veya paylaşmak istediğiniz bir durum..."/></label><button>Randevu talebi gönder →</button>{sent&&<p className="success">Talebiniz kaydedildi. WhatsApp üzerinden gönderebilirsiniz.</p>}</form></section>
  <footer id="iletisim"><a className="logo" href="#top">No.11<small>PILATES STUDIO</small></a><div><small>ADRES</small><p>Balat Mh. Alan Sk. No:9B<br/>Nilüfer / Bursa</p></div><div><small>İLETİŞİM</small><a href="tel:+905325159211">0 532 515 92 11</a><a href="https://instagram.com/no11.pilatesstudio">@no11.pilatesstudio</a></div><a href="/admin">Yönetici</a></footer>
 </main>
}
