'use client';
import {useEffect,useRef,useState} from 'react';

const services=['Birebir Pilates','Duet / İkili Pilates','Hamile Pilatesi','Omurga Odaklı Pilates','Tanışma Dersi'];
const times=['09:00','10:30','12:00','14:00','16:30','18:00','19:30'];

export default function HomePage(){
 const [menu,setMenu]=useState(false),[sent,setSent]=useState(false),[heroPaused,setHeroPaused]=useState(false);
 const desktopHero=useRef(null),mobileHero=useRef(null);
 useEffect(()=>{ document.body.style.overflow=menu?'hidden':''; return()=>{document.body.style.overflow=''} },[menu]);
 useEffect(()=>{ const setup=(v)=>{if(!v)return;v.muted=true;v.defaultMuted=true;v.loop=true;v.playsInline=true;v.controls=false;v.defaultPlaybackRate=.9;v.playbackRate=.9}; setup(desktopHero.current);setup(mobileHero.current);const play=()=>{const v=window.matchMedia('(min-width: 901px)').matches?desktopHero.current:mobileHero.current;if(v)v.play().then(()=>setHeroPaused(false)).catch(()=>{})};play();window.addEventListener('pageshow',play);return()=>window.removeEventListener('pageshow',play)},[]);
 function toggleHero(){const v=window.matchMedia('(min-width: 901px)').matches?desktopHero.current:mobileHero.current;if(!v)return;if(v.paused)v.play().then(()=>setHeroPaused(false)).catch(()=>{});else{v.pause();setHeroPaused(true)}}
 async function submit(e){
   e.preventDefault(); const f=new FormData(e.currentTarget);
   const appointment={id:'NO11-'+String(Date.now()).slice(-6),name:String(f.get('name')||''),phone:String(f.get('phone')||''),email:String(f.get('email')||''),service:String(f.get('service')||'Tanışma Dersi'),date:String(f.get('date')||''),time:String(f.get('time')||''),studentNote:String(f.get('note')||''),note:String(f.get('note')||''),managerNote:'',status:'pending',createdAt:new Date().toISOString()};
   try{const res=await fetch('/api/no11-appointments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(appointment)});if(!res.ok){const data=await res.json().catch(()=>({}));throw new Error(data.error||'Randevu oluşturulamadı');}}catch(err){alert(err.message||'Randevu oluşturulamadı');return;}
   const text=`Merhaba No.11 Pilates Studio, randevu talebi oluşturmak istiyorum.\n\nAd Soyad: ${appointment.name}\nTelefon: ${appointment.phone}\nDers: ${appointment.service}\nTarih: ${appointment.date}\nSaat: ${appointment.time}\nNot: ${appointment.studentNote}`;
   setSent(true); window.open('https://wa.me/905325159211?text='+encodeURIComponent(text),'_blank','noopener,noreferrer'); e.currentTarget.reset();
 }
 return <main>
  <header className="site-nav"><a className="logo" href="#top">No.11<small>PILATES STUDIO</small></a><nav>{['hikaye','deneyim','studyo','ekip','iletisim'].map(x=><a key={x} href={'#'+x}>{({hikaye:'Hikâyemiz',deneyim:'Deneyim',studyo:'Stüdyo',ekip:'Ekip',iletisim:'İletişim'})[x]}</a>)}</nav><a className="nav-cta" href="#randevu">Randevu Al →</a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Menüyü aç"><span/><span/><span/></button></header>
  {menu&&<div className="mobile-menu">{['hikaye','deneyim','studyo','ekip','iletisim','randevu'].map(x=><a onClick={()=>setMenu(false)} key={x} href={'#'+x}>{x==='randevu'?'Randevu Al':x[0].toUpperCase()+x.slice(1)} <span>→</span></a>)}</div>}
  <section id="top" className="hero"><video ref={desktopHero} className="hero-video hero-video--desktop desktop-video" autoPlay muted loop playsInline poster="/no11-desktop-poster.webp"><source src="/no11-desktop-full-quality.mp4" type="video/mp4"/></video><video ref={mobileHero} className="hero-video hero-video--mobile mobile-video" autoPlay muted loop playsInline><source src="/no11-mobile-full-quality.mp4" type="video/mp4"/></video><div className="hero-shade"/><div className="hero-mobile-copy"><div className="hero-rule"><span>11</span></div><p>NO.11 PILATES STUDIO</p><h1>Kendinize ayırdığınız en iyi saat.</h1><a href="#randevu"><b>RANDEVU AL</b><i>→</i></a></div><div className="hero-copy"><div className="hero-desktop-rule"><span>11</span></div><p>NO.11 PILATES STUDIO</p><h1>Kendinize ayırdığınız en iyi saat.</h1></div><button className="no11-video-control" type="button" onClick={toggleHero} aria-label={heroPaused?"Videoyu oynat":"Videoyu durdur"}>{heroPaused?"▶":"Ⅱ"}</button></section>
  <section id="hikaye" className="section story"><p className="eyebrow">NO.11'İN HİKÂYESİ</p><div className="story-grid"><h2>Yalnızca<br/>bir sayı<br/><em>değil.</em></h2><div><p className="lead">No.11; anıların, yolculuğun ve hayallerin simgesi. Güçlü sezgiyi, dengeyi, ilhamı ve rehberliği temsil eden kişiye özel bir hareket alanı.</p><div className="principles">{[['01','Sezgi','Kendi bedeninizi ve ihtiyaçlarınızı dinleme sanatı.'],['02','Denge','Fiziksel ve zihinsel bütünlüğün sağlandığı nokta.'],['03','Rehberlik','Uzman ellerde, size özel tasarlanmış bir yolculuk.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></div></section>
  <section id="deneyim" className="experience"><img src="https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/guidance.webp" alt="Kişiye özel pilates çalışması"/><div><p className="eyebrow">STÜDYO DENEYİMİ</p><h2>Burada her şey<br/><em>kişiye özeldir.</em></h2><p>Her ayrıntı düşünülür, her hareketin bir amacı vardır. Bedeninize özenle yaklaşan bir sistem sizi bekler.</p><a href="#randevu">Deneyimi planlayın →</a></div></section>
  <section id="studyo" className="section studio"><div className="gallery-heading"><p className="eyebrow">STÜDYOMUZ</p><h2>Size ayrılmış <em>bir alan.</em></h2></div><button className="gallery-main gallery-photo" type="button"><img src="/no11-studio-main.jpeg" alt="No.11 Pilates Studio gün ışığı alan iç mekânı"/></button><div className="gallery-pair"><button className="gallery-photo" type="button"><img src="/no11-studio-detail-01.jpeg" alt="No.11 Pilates Studio Cadillac ve reformer alanı"/></button><button className="gallery-photo" type="button"><img src="/no11-studio-detail-02.jpeg" alt="No.11 Pilates Studio gün ışığı alan çalışma bölümü"/></button><button className="gallery-photo" type="button"><img src="/no11-studio-detail-03.jpeg" alt="No.11 Pilates Studio karşılama alanı"/></button><button className="gallery-photo" type="button"><img src="/no11-studio-detail-04.jpeg" alt="No.11 Pilates Studio ahşap bölmeli iç mekânı"/></button></div></section>
  <section id="ekip" className="section team"><p className="eyebrow">UZMAN REHBERLİK</p><div className="founder"><div className="founder-image"><img src="https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/eda.webp" alt="Eda Dinçer"/></div><div className="founder-copy"><span>KURUCU · EĞİTMEN</span><h2>Eda Dinçer</h2><p>13 yıldır Pilates eğitmenliği yapan Eda Dinçer, Türkiye Cimnastik Federasyonu 1. ve 2. Kademe Pilates Antrenörüdür. Classical Pilates metoduyla kişiye özel, güvenli ve dengeli çalışmalar yürütür.</p></div></div></section>
  <section className="quote-band"><img src="https://no11-pilates-studio.yasar-aysenisa.chatgpt.site/images/movement.webp" alt="Klasik pilates hareketi"/><div><p>DENEMEDEN</p><h2>Bilemezsiniz.</h2><span>Değişim, karar verdiğiniz anda başlar.</span></div></section>
  <section id="randevu" className="section booking"><div><p className="eyebrow">İLK ADIM</p><h2>Size ayrılmış<br/><em>bir zaman.</em></h2><p>Formu doldurun; No.11 ekibi talebinizi değerlendirip sizinle iletişime geçsin.</p></div><form className="booking-form" onSubmit={submit}><label>Adınız Soyadınız<input required name="name" placeholder="Ad Soyad"/></label><div className="form-row"><label>Telefon<input required name="phone" type="tel" placeholder="05xx xxx xx xx"/></label><label>E-posta <small>(isteğe bağlı)</small><input name="email" type="email" placeholder="ornek@email.com"/></label></div><label>Ders tercihiniz<select required name="service" defaultValue=""><option value="" disabled>Bir ders türü seçin</option>{services.map(x=><option key={x}>{x}</option>)}</select></label><div className="form-row"><label>Tarih<input required name="date" type="date"/></label><label>Saat<select required name="time" defaultValue=""><option value="" disabled>Saat seçin</option>{times.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Notunuz <small>(isteğe bağlı)</small><textarea name="note" placeholder="Varsa hedefiniz veya paylaşmak istediğiniz bir durum..."/></label><button>Randevu talebi gönder →</button>{sent&&<p className="success">Talebiniz kaydedildi. WhatsApp üzerinden gönderebilirsiniz.</p>}</form></section>
  <footer id="iletisim" className="contact-footer"><div className="footer-mobile-head"><a className="footer-mobile-logo" href="#top">No.11<small>PILATES STUDIO</small></a><div className="footer-open-status"><span>Pazar</span><small>Kapalı</small></div><button className="footer-menu-mark" type="button" aria-label="Menü"><i></i><i></i><i></i></button></div><div className="footer-brand"><a className="logo" href="#top">No.11<small>PILATES STUDIO</small></a><p>BİZE ULAŞIN</p></div><a className="footer-map footer-map-card" href="https://www.google.com/maps/search/?api=1&query=No.11%20Pilates%20Studio%2C%20Balat%2C%20Alan%20Sk.%20No%3A9B%2C%2016225%20Nil%C3%BCfer%2FBursa" target="_blank" rel="noreferrer" aria-label="No.11 Pilates Studio konumunu Google Maps'te aç"><iframe title="No.11 Pilates Studio harita" src="https://www.google.com/maps?q=No.11%20Pilates%20Studio%2C%20Balat%2C%20Alan%20Sk.%20No%3A9B%2C%2016225%20Nil%C3%BCfer%2FBursa&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" tabIndex="-1"></iframe><span className="map-open">GOOGLE MAPS <b>→</b></span></a><div className="footer-address"><small>ADRES</small><address>Balat Mh. Alan Sk. No:9B<br/><span>Nilüfer / Bursa</span></address><div className="hours"><small>ÇALIŞMA SAATLERİ</small><p><span>Hafta içi</span><b>07.00 - 21.00</b></p><p><span>Cumartesi</span><b>09.00 - 18.00</b></p><p><span>Pazar</span><b>Kapalı</b></p></div></div><div className="footer-contact-grid"><small>TELEFON</small><a href="tel:+905325159211"><strong>0 532 515 92 11</strong></a><a href="https://wa.me/905325159211" target="_blank" rel="noreferrer">WhatsApp</a><a href="https://instagram.com/no11.pilatesstudio" target="_blank" rel="noreferrer"><strong>@no11.pilatesstudio</strong></a><a className="footer-book" href="#randevu">RANDEVU AL <span>→</span></a></div><div className="footer-links"><a href="/api/no11-admin-logout?next=/admin">YÖNETİCİ</a></div><div className="footer-copy">© 2026 NO.11 PILATES STUDIO</div></footer>
  <script src="/no11-team-live.js?v=3" defer></script><script src="/no11-studio-gallery.js?v=1" defer></script><script src="/no11-schedule-live.js?v=4" defer></script><script src="/no11-settings-live.js?v=6" defer></script>
 </main>
}